##' Compare viral and human protein degree distribution, filter by interaction detection method or PMIDs
##' @name humanViralDegree
##' @author Vitalii Kleshchevnikov
##' @description subset molecular interaction data (cleaned MITAB format in a data.table object) with a list of interactors
##' @param data a list contatining PPI data as generated by \code{\link[MItools]{loadHumanViralPPI}}, if NULL, data will be downloaded internally
##' @param directory where to find / keep PPI data (arg for \code{\link[MItools]{fullInteractome}}, \code{\link[MItools]{interSpeciesInteractome}})) and MI ontology (arg for \code{\link[MItools]{subsetMITABbyMethod}})
##' @param Interaction_detection_methods arg for \code{\link[MItools]{subsetMITABbyMethod}}
##' @param Identification_method arg for \code{\link[MItools]{subsetMITABbyMethod}}
##' @param PMIDs arg for \code{\link[MItools]{subsetMITABbyPMIDs}}
##' @param inverse_filter logical, inverse filtering criteria
##' @return data.table to be ggplotted to compare viral and human protein degree distributions
##' @import data.table
##' @export humanViralDegree
##' @examples
##' # Load data. This can be done internally by humanViralDegree(),
##' # however, it takes time (minutes) so it's recommended to load data separately if it will be used multiple times
##' HumanViralPPI = loadHumanViralPPI(directory = "./data_files/")
##'
##' # prepare all data for the degree distribution analysis
##' degree_distributions = humanViralDegree(data = HumanViralPPI, directory = "./data_files/")
##'
##' # prepare two-hybrid data for the degree distribution analysis
##' degree_distributions = humanViralDegree(data = HumanViralPPI, directory = "./data_files/", Interaction_detection_methods = "MI:0018")
##'
##' # prepare AP-MS data for the degree distribution analysis
##' degree_distributions = humanViralDegree(data = HumanViralPPI, directory = "./data_files/", Interaction_detection_methods = "MI:0004", Identification_method = "MI:0433", PMIDs = NULL, inverse_filter = F)
##'
##' # to see if viral-interacting human proteins are special in the human network, look at the Vidal published and unpublished datasets (only human-human network is modified (data for the top 2 plots))
##' degree_distributions = humanViralDegree(data = HumanViralPPI, directory = "./data_files/", PMIDs = c("25416956", "unassigned1304"))
##' # to see if viral-interacting human proteins are special in the human network, do the same for Matthias Mann 2015 paper dataset
##' degree_distributions = humanViralDegree(data = HumanViralPPI, directory = "./data_files/", PMIDs = "26496610")
humanViralDegree = function(data = NULL, directory = "./data_files/", Interaction_detection_methods = NULL, Identification_method = NULL, PMIDs = NULL, inverse_filter = F){

  if(is.null(data)){
    HumanViralPPI = loadHumanViralPPI(directory = directory)
  } else {
    HumanViralPPI = data
  }


  all_human_interaction = HumanViralPPI$human_human
  all_viral_interaction = HumanViralPPI$human_viral
  all_within_viral_interaction = HumanViralPPI$viral_viral

  # filter by method
  all_human_interaction = subsetMITABbyMethod(all_human_interaction,
                                              Interaction_detection_methods = Interaction_detection_methods,
                                              Identification_method = Identification_method, ontology_directory = directory,
                                              inverse_filter = inverse_filter)
  all_viral_interaction = subsetMITABbyMethod(all_viral_interaction,
                                              Interaction_detection_methods = Interaction_detection_methods,
                                              Identification_method = Identification_method, ontology_directory = directory,
                                              inverse_filter = inverse_filter)
  all_within_viral_interaction = subsetMITABbyMethod(all_within_viral_interaction,
                                                     Interaction_detection_methods = Interaction_detection_methods,
                                                     Identification_method = Identification_method, ontology_directory = directory,
                                                     inverse_filter = inverse_filter)
  # filter all_human_interaction by PMIDs
  if(!is.null(PMIDs)){
    all_human_interaction = subsetMITABbyPMIDs(MITABdata = all_human_interaction,
                                               PMIDs = PMIDs,
                                               inverse_filter = inverse_filter)
  }


  human_viral_proteins = extractInteractors(all_viral_interaction, taxid = 9606, not = F)
  human_human_proteins = extractInteractors(all_human_interaction)
  viral_proteins = extractInteractors(all_viral_interaction, taxid = 9606, not = T)

  human_human_degree = edgelist2degree(all_human_interaction$data)
  human_human_degree_legend = paste0("full human-human: \n", NuniqueInteractions(all_human_interaction)," interacting pairs, \n", NuniqueInteractors(all_human_interaction)," human proteins")
  human_human_degree[, legend := human_human_degree_legend]

  inViral_human_interaction = subsetMITABbyID(MITABdata = all_human_interaction,
                                              ID_seed = human_viral_proteins, within_seed = T)
  inViral_human_human_degree = edgelist2degree(inViral_human_interaction$data)[ID %in% human_viral_proteins]
  inViral_human_human_degree_legend = paste0("viral-interacting proteins, human-human: \n", NuniqueInteractions(inViral_human_interaction)," interacting pairs, \n", NuniqueInteractors(inViral_human_interaction)," human proteins")
  inViral_human_human_degree[, legend := inViral_human_human_degree_legend]

  inViral_human_viral_degree = edgelist2degree(all_viral_interaction$data)[ID %in% human_viral_proteins]
  inViral_human_viral_degree_legend = paste0("human-viral: \n", NuniqueInteractions(all_viral_interaction)," interacting pairs, \n", NuniqueInteractors(all_viral_interaction, taxid = 9606, not = F)," human proteins")
  inViral_human_viral_degree[, legend := inViral_human_viral_degree_legend]

  inViral_viral_human_degree = edgelist2degree(all_viral_interaction$data)[ID %in% viral_proteins]
  inViral_viral_human_degree_legend = paste0("viral-human: \n", NuniqueInteractions(all_viral_interaction)," interacting pairs, \n", NuniqueInteractors(all_viral_interaction, taxid = 9606, not = T)," viral proteins")
  inViral_viral_human_degree[, legend := inViral_viral_human_degree_legend]

  inViral_viral_viral_degree = edgelist2degree(all_within_viral_interaction$data)[ID %in% viral_proteins]
  inViral_viral_viral_degree_legend = paste0("viral-viral (human host) \n", NuniqueInteractions(all_within_viral_interaction)," interacting pairs, \n", NuniqueInteractors(all_within_viral_interaction)," viral proteins")
  inViral_viral_viral_degree[, legend := inViral_viral_viral_degree_legend]

  degree_distributions = rbind(human_human_degree, inViral_human_human_degree, inViral_human_viral_degree, inViral_viral_human_degree, inViral_viral_viral_degree)
  degree_distributions[, legend := factor(legend,
                                          levels = c(human_human_degree_legend,
                                                     inViral_viral_human_degree_legend, inViral_human_viral_degree_legend,
                                                     inViral_human_human_degree_legend, inViral_viral_viral_degree_legend))]
  degree_distributions[, medianN := as.integer(median(N)), by = legend]
  degree_distributions[, medianN_lab := paste0("median: ",signif(medianN,1), " interacting partners")]
  return(degree_distributions)
}

##' load human-human, human-viral and viral-viral PPI data from IntActFTP
##' @name loadHumanViralPPI
##' @author Vitalii Kleshchevnikov
##' @description use \code{\link[MItools]{interSpeciesInteractome}} and \code{\link[MItools]{fullInteractome}} to retrieve and load human-human, human-viral and viral-viral PPI data from IntActFTP
##' @description to be used with \code{\link[MItools]{humanViralDegree}}
##' @param where to find / keep PPI data (arg for \code{\link[MItools]{fullInteractome}}, \code{\link[MItools]{interSpeciesInteractome}}))
##' @import data.table
##' @export loadHumanViralPPI
loadHumanViralPPI = function(directory = "./data_files/"){
  # load ppi data
  # human-human
  all_human_interaction = fullInteractome(taxid = 9606, database = "IntActFTP", format = "tab27",
                                          clean = TRUE, protein_only = TRUE, directory = directory)

  # human-viral
  all_viral_interaction = interSpeciesInteractome(taxid1 = 9606, taxid2 = 10239, database = "IntActFTP", format = "tab27",
                                                  clean = TRUE, protein_only = TRUE, directory = directory)
  # viral-viral
  all_within_viral_interaction = fullInteractome(taxid = 10239, database = "IntActFTP", format = "tab27",
                                                 clean = TRUE, protein_only = TRUE, directory = directory)
  HumanViralPPI = list(human_human = all_human_interaction, human_viral = all_viral_interaction, viral_viral = all_within_viral_interaction)
  return(HumanViralPPI)
}
