##' Run a list of QSLIMFinder jobs
##' @rdname runQSLIMFinder
##' @name runQSLIMFinder
##' @author Vitalii Kleshchevnikov
##' @param file_list data.table containing path to files and directories for QSLIMFinder: fastafile, queryfile, outputdir, outputfile
##' @param commands character vector of commands generated by \code{\link{QSLIMFinderCommand}} that will launch QSLIMFinder jobs
##' @param max_memory max memory to use for a job
##' @param onLSF use LSF cluster to run QSLIMFinder jobs
##' @param recursive how to create directories
##' @return list: character vector, commands that have crashed even at \code{max_memory}; data.table, corresponding rows of \code{file_list}
##' @import data.table
##' @export runQSLIMFinder
##' @seealso \code{\link{QSLIMFinderCommand}}
runQSLIMFinder = function(commands, file_list, max_memory = 5000, onLSF = T, recursive = F){
  if(mean(c("set_env_var","run") %in% names(commands)) < 1) stop("`commands` doesn't contain `set_env_var` and/or `run`, check that `commands` is an output of mQSLIMFinderCommand")
  if(onLSF){
    # create dirs for stout and sterr
    if(!is.null(commands$log_dirfull)) if(!dir.exists(commands$log_dirfull)) dir.create(commands$log_dirfull, recursive = recursive)
    if(!is.null(commands$log_dirlog)) if(!dir.exists(commands$log_dirlog)) dir.create(commands$log_dirlog, recursive = recursive)
    if(!is.null(commands$log_direrror)) if(!dir.exists(commands$log_direrror)) dir.create(commands$log_direrror, recursive = recursive)

    # set up enviromental variable IUPred_PATH
    system(commands$set_env_var)
    # run runQSLIMFinder and wait until all jobs finish
    LSFrunQSLIMFinder(commands$run)
    # find which jobs have crashed
    commands_crashed = commands$run[!file.exists(file_list$outputfile)]

    memory_vals = seq(200, max_memory, 100)
    for(memory_val in memory_vals){
      if(length(commands_crashed) >= 1){
        commands_crashed = modifyMemoryInBsub(commands_crashed, memory = memory_val)
        LSFrunQSLIMFinder(commands_crashed)
        commands_crashed = commands$run[!file.exists(file_list$outputfile)]
      }
    }
return((commands_crashed))
  } else {stop("onLSF = F not implemented") }
}


##' @rdname runQSLIMFinder
##' @name modifyMemoryInBsub
##' @param memory integer, how much memory should the job use
##' @import data.table
##' @export modifyMemoryInBsub
modifyMemoryInBsub = function(commands, memory){
  commands = gsub("-M [[:digit:]]+ ",paste0("-M ",memory," "),commands)
  commands = gsub("rusage\\[mem=[[:digit:]]+\\]",paste0("rusage\\[mem=",memory,"\\]"),commands)
  commands
}

##' @rdname runQSLIMFinder
##' @name LSFrunQSLIMFinder
##' @import data.table
##' @export LSFrunQSLIMFinder
LSFrunQSLIMFinder = function(commands) {
  for (command in commands) {
    Nbjobs = length(system("bjobs", intern =T)) - 1
    done = FALSE
    n = 1
    while(!done){
      if(Nbjobs < 490){
        system(command, wait = F)
        done = TRUE
        n = 1
      } else {
        n = n + 1
        Sys.sleep(n^1.6)
      }
    }
  }
  bjobs = system("bjobs", intern =T)
  while(sum(grepl("\\.fas", bjobs)) >= 1){
    bjobs = system("bjobs", intern =T)
    Sys.sleep(10)
  }
}
